family_parameters:
  avg_degree_range:
  - 2.0
  - 8.0
  degree_distribution: power_law
  degree_separation_range:
  - 0.4
  - 0.8
  homophily_range:
  - 0.1
  - 0.9
  max_communities: 7
  max_n_nodes: 200
  min_communities: 3
  min_n_nodes: 25
  n_graphs: 100
  power_law_exponent_range:
  - 2.0
  - 3.0
  seed: 42
tasks:
- community_detection
- triangle_counting
universe_parameters:
  K: 10
  center_variance: 1.0
  cluster_variance: 0.3
  edge_propensity_variance: 0.5
  feature_dim: 16
  seed: 42
